#!/bin/bash

set -e

ENV_FILE="./environment/.env.production"

# Write the .env file
cat >"$ENV_FILE" <<EOF
VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}
VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
VITE_FIREBASE_APP_ID=${FIREBASE_APP_ID}
VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
VITE_CHAT_API_URL=${CHAT_API_URL}
EOF

echo ".env.production file created successfully at $ENV_FILE"
